typography_spectrum: 0.360514092259109
color:
  brandStrength: 0.9512237133458257
  lightness: 0.5534260820131749
  saturation: 0.44269166933372617
  rhythmicContrast: 0.816690711537376
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.2231508744880557
author:
  name: bweave
  email: bob@bweave.com
  url: teamdreamweaver.info
name: Team Dream Weaver
title: 'Your Dream, Our Team'
description: We Are Here for You - teamdreamweaver.info
